apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-wizardry
  namespace: money-wizardry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-wizardry
  template:
    metadata:
      labels:
        app: money-wizardry
    spec:
      containers:
      - name: money-wizardry
        image: europe-west1-docker.pkg.dev/money-wizardry-prod/money-wizardry-repo/app:latest
        ports:
        - containerPort: 80
        
        envFrom:
        - configMapRef:
            name: money-wizardry-config
        
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: money-wizardry-secrets
              key: APP_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: money-wizardry-secrets
              key: DB_PASSWORD
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: money-wizardry-secrets
              key: TELEGRAM_BOT_TOKEN
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
          failureThreshold: 5
        
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5