apiVersion: v1
kind: Secret
metadata:
  name: money-wizardry-secrets
  namespace: money-wizardry
type: Opaque
stringData:
  APP_KEY: "base64:Vy6KXPj8wUy/1u3fCM8AC5NS+igmvUA56crXgiOCeos="
  DB_PASSWORD: "{D=:D8,E-6yeT_jb"
  TELEGRAM_BOT_TOKEN: "8419620401:AAG76c1DKK5yhVJtSqOpC8C9SZ19BXQpbm4"